channels:
- conda-forge
dependencies:
- python=3.8.5
- pip<=20.1.1
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - colorama==0.4.5
  - dask==2.30.0
  - dataclasses==0.6
  - lz4==4.0.2
  - psutil==5.9.1
  - scikit-learn==0.22.1
  - sparse==0.13.0
  - tblib==1.7.0
  - toolz==0.12.0
  - typing-extensions==4.3.0
  - uuid==1.30
  - xgboost==1.3.3
  - xxhash==3.0.0
name: mlflow-env
